#!/usr/bin/env python3
"""
Facebook + Instagram Integration

Social media posting automation with Mock Mode support.
All posts require HITL approval before publishing.

Usage:
    python3 facebook_instagram.py --post-fb "Your message"   # Post to Facebook
    python3 facebook_instagram.py --post-ig "Your message"   # Post to Instagram
    python3 facebook_instagram.py --summary                   # Weekly summary
    python3 facebook_instagram.py --demo                      # Run demo
    python3 facebook_instagram.py --history fb                # View FB history
    python3 facebook_instagram.py --history ig                # View IG history
    python3 facebook_instagram.py --status                    # Check status

Mock Mode (default):
    - Simulates posting without real API calls
    - Full HITL approval workflow
    - Posts saved to /Social_Media/ folder
"""

import os
import sys
import json
import logging
import hashlib
import shutil
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional

# === Configuration ===
BASE_DIR = Path(__file__).parent
SOCIAL_MEDIA_DIR = BASE_DIR / "Social_Media"
PENDING_APPROVAL_DIR = BASE_DIR / "Pending_Approval"
APPROVED_DIR = BASE_DIR / "Approved"
REJECTED_DIR = BASE_DIR / "Rejected"
LOGS_DIR = BASE_DIR / "Logs"

FACEBOOK_POSTS_FILE = SOCIAL_MEDIA_DIR / "facebook_posts.md"
INSTAGRAM_POSTS_FILE = SOCIAL_MEDIA_DIR / "instagram_posts.md"
SOCIAL_MEDIA_LOG = LOGS_DIR / "social_media.log"

# Mock Mode - set to False when real API is configured
MOCK_MODE = os.environ.get("SOCIAL_MEDIA_MOCK_MODE", "true").lower() == "true"

# === Logging Setup ===
LOGS_DIR.mkdir(exist_ok=True)
SOCIAL_MEDIA_DIR.mkdir(exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)s | %(message)s',
    handlers=[
        logging.FileHandler(SOCIAL_MEDIA_LOG),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)


# === Utility Functions ===

def generate_post_id(platform: str) -> str:
    """Generate unique post ID."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    unique = hashlib.md5(f"{platform}{timestamp}{os.urandom(4).hex()}".encode()).hexdigest()[:8]
    prefix = "FB" if platform == "facebook" else "IG"
    return f"{prefix}_{timestamp}_{unique}"


def extract_hashtags(content: str) -> List[str]:
    """Extract hashtags from content."""
    words = content.split()
    return [word for word in words if word.startswith("#")]


def create_approval_request(
    platform: str,
    content: str,
    post_type: str = "text_post",
    hashtags: List[str] = None
) -> Path:
    """Create HITL approval request for social media post."""
    PENDING_APPROVAL_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now()
    post_id = generate_post_id(platform)

    # Truncate content for filename
    content_slug = content[:30].replace(" ", "_").replace("/", "_")
    content_slug = "".join(c for c in content_slug if c.isalnum() or c == "_")

    filename = f"SOCIAL_MEDIA_POST_{platform.capitalize()}_{content_slug}_{timestamp.strftime('%Y%m%d_%H%M%S')}.json"

    approval_data = {
        "action_type": "SOCIAL_MEDIA_POST",
        "platform": platform,
        "post_type": post_type,
        "post_id": post_id,
        "content": content,
        "hashtags": hashtags or extract_hashtags(content),
        "scheduled_time": None,
        "mock_mode": MOCK_MODE,
        "requires_approval": True,
        "created_at": timestamp.isoformat() + "Z",
        "expires_at": (timestamp + timedelta(hours=24)).isoformat() + "Z",
        "description": f"{platform.capitalize()} post: {content[:50]}..."
    }

    filepath = PENDING_APPROVAL_DIR / filename
    filepath.write_text(json.dumps(approval_data, indent=2))

    logger.info(f"Approval request created: {filename}")
    return filepath


def save_post_to_history(
    platform: str,
    post_id: str,
    content: str,
    hashtags: List[str] = None,
    status: str = "Published"
) -> None:
    """Save published post to history file."""
    SOCIAL_MEDIA_DIR.mkdir(exist_ok=True)

    history_file = FACEBOOK_POSTS_FILE if platform == "facebook" else INSTAGRAM_POSTS_FILE
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Create header if file doesn't exist
    if not history_file.exists():
        header = f"# {platform.capitalize()} Post History\n\n"
        header += f"*Generated by AI Employee Social Media Integration*\n\n"
        header += "---\n\n"
        history_file.write_text(header)

    # Append post entry
    mode_indicator = " (Mock Mode)" if MOCK_MODE else ""
    hashtag_str = " ".join(hashtags) if hashtags else "None"

    entry = f"""## {timestamp}

**Post ID:** {post_id}
**Status:** {status}{mode_indicator}
**Content:**
{content}

**Hashtags:** {hashtag_str}
**Engagement:** 0 likes, 0 comments{", 0 shares" if platform == "facebook" else ""} ({"simulated" if MOCK_MODE else "pending"})

---

"""

    with open(history_file, "a") as f:
        f.write(entry)

    logger.info(f"Post saved to history: {post_id}")


def mock_publish_post(platform: str, post_id: str, content: str, hashtags: List[str] = None) -> Dict[str, Any]:
    """Simulate publishing a post (Mock Mode)."""
    logger.info(f"[MOCK] Publishing to {platform}: {post_id}")

    # Simulate API response
    response = {
        "success": True,
        "post_id": post_id,
        "platform": platform,
        "mock_mode": True,
        "timestamp": datetime.now().isoformat(),
        "message": f"Post simulated successfully on {platform}"
    }

    # Save to history
    save_post_to_history(platform, post_id, content, hashtags, "Published")

    return response


# === Main Functions ===

def post_to_facebook(content: str, auto_approve: bool = False) -> Dict[str, Any]:
    """
    Create a Facebook post request.

    Args:
        content: The post content
        auto_approve: If True, automatically approve (for demo only)

    Returns:
        Dict with status and details
    """
    logger.info(f"Creating Facebook post request: {content[:50]}...")

    hashtags = extract_hashtags(content)

    # Create approval request
    approval_path = create_approval_request("facebook", content, "text_post", hashtags)

    result = {
        "status": "pending_approval",
        "platform": "facebook",
        "approval_file": str(approval_path),
        "content": content,
        "hashtags": hashtags,
        "mock_mode": MOCK_MODE
    }

    if auto_approve:
        # Move to approved and execute
        approved_path = APPROVED_DIR / approval_path.name
        APPROVED_DIR.mkdir(exist_ok=True)
        shutil.move(str(approval_path), str(approved_path))

        # Load and publish
        data = json.loads(approved_path.read_text())
        publish_result = mock_publish_post(
            "facebook",
            data["post_id"],
            data["content"],
            data["hashtags"]
        )

        result["status"] = "published"
        result["publish_result"] = publish_result

    return result


def post_to_instagram(content: str, auto_approve: bool = False) -> Dict[str, Any]:
    """
    Create an Instagram post request.

    Args:
        content: The post caption
        auto_approve: If True, automatically approve (for demo only)

    Returns:
        Dict with status and details
    """
    logger.info(f"Creating Instagram post request: {content[:50]}...")

    hashtags = extract_hashtags(content)

    # Create approval request
    approval_path = create_approval_request("instagram", content, "text_post", hashtags)

    result = {
        "status": "pending_approval",
        "platform": "instagram",
        "approval_file": str(approval_path),
        "content": content,
        "hashtags": hashtags,
        "mock_mode": MOCK_MODE
    }

    if auto_approve:
        # Move to approved and execute
        approved_path = APPROVED_DIR / approval_path.name
        APPROVED_DIR.mkdir(exist_ok=True)
        shutil.move(str(approval_path), str(approved_path))

        # Load and publish
        data = json.loads(approved_path.read_text())
        publish_result = mock_publish_post(
            "instagram",
            data["post_id"],
            data["content"],
            data["hashtags"]
        )

        result["status"] = "published"
        result["publish_result"] = publish_result

    return result


def get_weekly_summary() -> Dict[str, Any]:
    """Generate weekly summary of social media posts."""
    summary = {
        "period": {
            "start": (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d"),
            "end": datetime.now().strftime("%Y-%m-%d")
        },
        "facebook": {
            "posts": 0,
            "engagement": {"likes": 0, "comments": 0, "shares": 0}
        },
        "instagram": {
            "posts": 0,
            "engagement": {"likes": 0, "comments": 0}
        },
        "pending_approvals": 0,
        "rejected": 0
    }

    # Count Facebook posts
    if FACEBOOK_POSTS_FILE.exists():
        content = FACEBOOK_POSTS_FILE.read_text()
        summary["facebook"]["posts"] = content.count("**Post ID:** FB_")

    # Count Instagram posts
    if INSTAGRAM_POSTS_FILE.exists():
        content = INSTAGRAM_POSTS_FILE.read_text()
        summary["instagram"]["posts"] = content.count("**Post ID:** IG_")

    # Count pending approvals
    if PENDING_APPROVAL_DIR.exists():
        for f in PENDING_APPROVAL_DIR.glob("SOCIAL_MEDIA_POST_*.json"):
            summary["pending_approvals"] += 1

    # Count rejected
    if REJECTED_DIR.exists():
        for f in REJECTED_DIR.glob("SOCIAL_MEDIA_POST_*.json"):
            summary["rejected"] += 1

    return summary


def show_summary():
    """Display weekly summary."""
    summary = get_weekly_summary()

    print("\n" + "="*60)
    print("SOCIAL MEDIA WEEKLY SUMMARY")
    print("="*60)
    print(f"Period: {summary['period']['start']} to {summary['period']['end']}")
    print(f"Mode: {'MOCK' if MOCK_MODE else 'PRODUCTION'}")
    print()

    print("FACEBOOK")
    print(f"  Posts: {summary['facebook']['posts']}")
    print(f"  Likes: {summary['facebook']['engagement']['likes']}")
    print(f"  Comments: {summary['facebook']['engagement']['comments']}")
    print(f"  Shares: {summary['facebook']['engagement']['shares']}")
    print()

    print("INSTAGRAM")
    print(f"  Posts: {summary['instagram']['posts']}")
    print(f"  Likes: {summary['instagram']['engagement']['likes']}")
    print(f"  Comments: {summary['instagram']['engagement']['comments']}")
    print()

    print("WORKFLOW")
    print(f"  Pending Approvals: {summary['pending_approvals']}")
    print(f"  Rejected: {summary['rejected']}")

    print("="*60 + "\n")


def show_history(platform: str):
    """Display post history for a platform."""
    if platform == "fb" or platform == "facebook":
        history_file = FACEBOOK_POSTS_FILE
        platform_name = "Facebook"
    elif platform == "ig" or platform == "instagram":
        history_file = INSTAGRAM_POSTS_FILE
        platform_name = "Instagram"
    else:
        print(f"Unknown platform: {platform}")
        print("Use 'fb' for Facebook or 'ig' for Instagram")
        return

    print(f"\n{'='*60}")
    print(f"{platform_name.upper()} POST HISTORY")
    print("="*60 + "\n")

    if not history_file.exists():
        print(f"No {platform_name} posts yet.")
        return

    print(history_file.read_text())


def show_status():
    """Show current status of social media integration."""
    print("\n" + "="*60)
    print("SOCIAL MEDIA INTEGRATION STATUS")
    print("="*60)

    # Mode
    print(f"\nMode: {'MOCK (simulated)' if MOCK_MODE else 'PRODUCTION'}")

    # Files
    print("\nHistory Files:")
    if FACEBOOK_POSTS_FILE.exists():
        fb_count = FACEBOOK_POSTS_FILE.read_text().count("**Post ID:** FB_")
        print(f"  Facebook: {fb_count} posts")
    else:
        print("  Facebook: No posts yet")

    if INSTAGRAM_POSTS_FILE.exists():
        ig_count = INSTAGRAM_POSTS_FILE.read_text().count("**Post ID:** IG_")
        print(f"  Instagram: {ig_count} posts")
    else:
        print("  Instagram: No posts yet")

    # Pending
    print("\nPending Approvals:")
    if PENDING_APPROVAL_DIR.exists():
        pending = list(PENDING_APPROVAL_DIR.glob("SOCIAL_MEDIA_POST_*.json"))
        if pending:
            for f in pending[:5]:
                data = json.loads(f.read_text())
                print(f"  - {data['platform']}: {data['content'][:40]}...")
            if len(pending) > 5:
                print(f"  ... and {len(pending) - 5} more")
        else:
            print("  None")
    else:
        print("  None")

    print("\n" + "="*60)


def run_demo():
    """Run a full demo of Facebook and Instagram integration."""
    print("\n" + "="*60)
    print("FACEBOOK + INSTAGRAM INTEGRATION DEMO")
    print("="*60)
    print(f"Mode: {'MOCK (no real API calls)' if MOCK_MODE else 'PRODUCTION'}")
    print()

    # Demo 1: Facebook post
    print("[1/4] Creating Facebook post...")
    fb_content = "AI automation is transforming how businesses operate. Our latest integration brings intelligent scheduling and approval workflows to your social media strategy. #AI #Automation #BusinessTech"
    fb_result = post_to_facebook(fb_content, auto_approve=False)
    print(f"  Content: \"{fb_content[:50]}...\"")
    print(f"  Status: {fb_result['status']}")
    print(f"  Approval file: {Path(fb_result['approval_file']).name}")
    print()

    # Demo 2: Auto-approve and publish Facebook
    print("[2/4] Simulating Facebook approval...")
    # Move to approved
    fb_approval_path = Path(fb_result['approval_file'])
    if fb_approval_path.exists():
        APPROVED_DIR.mkdir(exist_ok=True)
        approved_path = APPROVED_DIR / fb_approval_path.name
        shutil.move(str(fb_approval_path), str(approved_path))
        print("  Moved to Approved folder")

        # Execute
        data = json.loads(approved_path.read_text())
        publish_result = mock_publish_post(
            "facebook",
            data["post_id"],
            data["content"],
            data["hashtags"]
        )
        print(f"  Post published (mock): {data['post_id']}")
    print()

    # Demo 3: Instagram post
    print("[3/4] Creating Instagram post...")
    ig_content = "Building intelligent systems that work while you sleep. The future of work is autonomous, efficient, and human-approved. #TechInnovation #FutureOfWork #AIEmployee"
    ig_result = post_to_instagram(ig_content, auto_approve=True)
    print(f"  Content: \"{ig_content[:50]}...\"")
    print(f"  Status: {ig_result['status']}")
    if ig_result.get('publish_result'):
        print(f"  Post ID: {ig_result['publish_result']['post_id']}")
    print()

    # Demo 4: Summary
    print("[4/4] Generating weekly summary...")
    summary = get_weekly_summary()
    print()
    print("  WEEKLY SUMMARY")
    print("  --------------")
    print(f"  Facebook: {summary['facebook']['posts']} posts")
    print(f"  Instagram: {summary['instagram']['posts']} posts")
    print(f"  Total engagement: 0 (mock mode)")
    print()

    print("Demo completed successfully!")
    print("="*60 + "\n")


# === Main Entry Point ===

if __name__ == "__main__":
    if len(sys.argv) > 1:
        arg = sys.argv[1]

        if arg == "--post-fb" and len(sys.argv) > 2:
            content = sys.argv[2]
            result = post_to_facebook(content)
            print(f"\nFacebook post request created!")
            print(f"Status: {result['status']}")
            print(f"Approval file: {Path(result['approval_file']).name}")
            print(f"\nTo approve: Move the file to /Approved/")
            print(f"To reject: Move the file to /Rejected/")

        elif arg == "--post-ig" and len(sys.argv) > 2:
            content = sys.argv[2]
            result = post_to_instagram(content)
            print(f"\nInstagram post request created!")
            print(f"Status: {result['status']}")
            print(f"Approval file: {Path(result['approval_file']).name}")
            print(f"\nTo approve: Move the file to /Approved/")
            print(f"To reject: Move the file to /Rejected/")

        elif arg == "--summary":
            show_summary()

        elif arg == "--history" and len(sys.argv) > 2:
            show_history(sys.argv[2])

        elif arg == "--status":
            show_status()

        elif arg == "--demo":
            run_demo()

        elif arg == "--help":
            print(__doc__)

        else:
            print(f"Unknown option: {arg}")
            print(__doc__)

    else:
        print(__doc__)
