#!/usr/bin/env python3
"""
Twitter/X Integration

Tweet posting automation with Mock Mode support.
All tweets require HITL approval before publishing.

Usage:
    python3 twitter_x.py --tweet "Your message"    # Post a tweet
    python3 twitter_x.py --summary                  # Weekly summary
    python3 twitter_x.py --demo                     # Run demo
    python3 twitter_x.py --history                  # View tweet history
    python3 twitter_x.py --status                   # Check status

Mock Mode (default):
    - Simulates posting without real API calls
    - Full HITL approval workflow
    - Tweets saved to /Social_Media/twitter_posts.md

Character Limit: 280 characters (warns if exceeded)
"""

import os
import sys
import json
import logging
import hashlib
import shutil
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional

# === Configuration ===
BASE_DIR = Path(__file__).parent
SOCIAL_MEDIA_DIR = BASE_DIR / "Social_Media"
PENDING_APPROVAL_DIR = BASE_DIR / "Pending_Approval"
APPROVED_DIR = BASE_DIR / "Approved"
REJECTED_DIR = BASE_DIR / "Rejected"
LOGS_DIR = BASE_DIR / "Logs"

TWITTER_POSTS_FILE = SOCIAL_MEDIA_DIR / "twitter_posts.md"
TWITTER_LOG = LOGS_DIR / "twitter.log"

# Twitter character limit
TWEET_CHAR_LIMIT = 280

# Mock Mode - set to False when real API is configured
MOCK_MODE = os.environ.get("TWITTER_MOCK_MODE", "true").lower() == "true"

# === Logging Setup ===
LOGS_DIR.mkdir(exist_ok=True)
SOCIAL_MEDIA_DIR.mkdir(exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)s | %(message)s',
    handlers=[
        logging.FileHandler(TWITTER_LOG),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)


# === Utility Functions ===

def generate_tweet_id() -> str:
    """Generate unique tweet ID."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    unique = hashlib.md5(f"twitter{timestamp}{os.urandom(4).hex()}".encode()).hexdigest()[:8]
    return f"TW_{timestamp}_{unique}"


def extract_hashtags(content: str) -> List[str]:
    """Extract hashtags from content."""
    words = content.split()
    return [word for word in words if word.startswith("#")]


def extract_mentions(content: str) -> List[str]:
    """Extract @mentions from content."""
    words = content.split()
    return [word for word in words if word.startswith("@")]


def validate_tweet_length(content: str) -> Dict[str, Any]:
    """Validate tweet length and return info."""
    length = len(content)
    return {
        "length": length,
        "limit": TWEET_CHAR_LIMIT,
        "remaining": TWEET_CHAR_LIMIT - length,
        "valid": length <= TWEET_CHAR_LIMIT,
        "warning": length > TWEET_CHAR_LIMIT
    }


def create_approval_request(content: str) -> Path:
    """Create HITL approval request for tweet."""
    PENDING_APPROVAL_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now()
    tweet_id = generate_tweet_id()

    # Truncate content for filename
    content_slug = content[:25].replace(" ", "_").replace("/", "_")
    content_slug = "".join(c for c in content_slug if c.isalnum() or c == "_")

    filename = f"TWEET_{content_slug}_{timestamp.strftime('%Y%m%d_%H%M%S')}.json"

    # Validate length
    length_info = validate_tweet_length(content)

    approval_data = {
        "action_type": "TWEET",
        "platform": "twitter",
        "tweet_id": tweet_id,
        "content": content,
        "character_count": length_info["length"],
        "character_limit": TWEET_CHAR_LIMIT,
        "exceeds_limit": length_info["warning"],
        "hashtags": extract_hashtags(content),
        "mentions": extract_mentions(content),
        "mock_mode": MOCK_MODE,
        "requires_approval": True,
        "created_at": timestamp.isoformat() + "Z",
        "expires_at": (timestamp + timedelta(hours=24)).isoformat() + "Z",
        "description": f"Tweet ({length_info['length']}/{TWEET_CHAR_LIMIT} chars): {content[:50]}..."
    }

    filepath = PENDING_APPROVAL_DIR / filename
    filepath.write_text(json.dumps(approval_data, indent=2))

    logger.info(f"Approval request created: {filename}")
    return filepath


def save_tweet_to_history(
    tweet_id: str,
    content: str,
    hashtags: List[str] = None,
    mentions: List[str] = None,
    status: str = "Published"
) -> None:
    """Save published tweet to history file."""
    SOCIAL_MEDIA_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    length_info = validate_tweet_length(content)

    # Create header if file doesn't exist
    if not TWITTER_POSTS_FILE.exists():
        header = "# Twitter/X Post History\n\n"
        header += "*Generated by AI Employee Twitter Integration*\n\n"
        header += "---\n\n"
        TWITTER_POSTS_FILE.write_text(header)

    # Format data
    mode_indicator = " (Mock Mode)" if MOCK_MODE else ""
    hashtag_str = " ".join(hashtags) if hashtags else "None"
    mention_str = " ".join(mentions) if mentions else "None"

    entry = f"""## {timestamp}

**Tweet ID:** {tweet_id}
**Status:** {status}{mode_indicator}
**Characters:** {length_info['length']}/{TWEET_CHAR_LIMIT}

**Content:**
{content}

**Hashtags:** {hashtag_str}
**Mentions:** {mention_str}
**Engagement:** 0 likes, 0 retweets, 0 replies ({"simulated" if MOCK_MODE else "pending"})

---

"""

    with open(TWITTER_POSTS_FILE, "a") as f:
        f.write(entry)

    logger.info(f"Tweet saved to history: {tweet_id}")


def mock_publish_tweet(tweet_id: str, content: str) -> Dict[str, Any]:
    """Simulate publishing a tweet (Mock Mode)."""
    logger.info(f"[MOCK] Publishing tweet: {tweet_id}")

    hashtags = extract_hashtags(content)
    mentions = extract_mentions(content)

    # Simulate API response
    response = {
        "success": True,
        "tweet_id": tweet_id,
        "platform": "twitter",
        "mock_mode": True,
        "timestamp": datetime.now().isoformat(),
        "character_count": len(content),
        "message": "Tweet simulated successfully"
    }

    # Save to history
    save_tweet_to_history(tweet_id, content, hashtags, mentions, "Published")

    return response


# === Main Functions ===

def post_tweet(content: str, auto_approve: bool = False) -> Dict[str, Any]:
    """
    Create a tweet request.

    Args:
        content: The tweet content (max 280 chars)
        auto_approve: If True, automatically approve (for demo only)

    Returns:
        Dict with status and details
    """
    # Validate length
    length_info = validate_tweet_length(content)

    if length_info["warning"]:
        logger.warning(f"Tweet exceeds {TWEET_CHAR_LIMIT} character limit: {length_info['length']} chars")
        print(f"\n  WARNING: Tweet is {length_info['length']} characters (limit: {TWEET_CHAR_LIMIT})")
        print(f"  Exceeds limit by {-length_info['remaining']} characters")
        print(f"  Tweet will be truncated or rejected by Twitter API\n")

    logger.info(f"Creating tweet request ({length_info['length']} chars): {content[:50]}...")

    hashtags = extract_hashtags(content)
    mentions = extract_mentions(content)

    # Create approval request
    approval_path = create_approval_request(content)

    result = {
        "status": "pending_approval",
        "platform": "twitter",
        "approval_file": str(approval_path),
        "content": content,
        "character_count": length_info["length"],
        "character_limit": TWEET_CHAR_LIMIT,
        "exceeds_limit": length_info["warning"],
        "hashtags": hashtags,
        "mentions": mentions,
        "mock_mode": MOCK_MODE
    }

    if auto_approve:
        # Move to approved and execute
        approved_path = APPROVED_DIR / approval_path.name
        APPROVED_DIR.mkdir(exist_ok=True)
        shutil.move(str(approval_path), str(approved_path))

        # Load and publish
        data = json.loads(approved_path.read_text())
        publish_result = mock_publish_tweet(data["tweet_id"], data["content"])

        result["status"] = "published"
        result["publish_result"] = publish_result

    return result


def get_weekly_summary() -> Dict[str, Any]:
    """Generate weekly summary of tweets."""
    summary = {
        "period": {
            "start": (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d"),
            "end": datetime.now().strftime("%Y-%m-%d")
        },
        "tweets": 0,
        "total_characters": 0,
        "avg_characters": 0,
        "engagement": {"likes": 0, "retweets": 0, "replies": 0},
        "pending_approvals": 0,
        "rejected": 0,
        "top_hashtags": []
    }

    # Count tweets
    if TWITTER_POSTS_FILE.exists():
        content = TWITTER_POSTS_FILE.read_text()
        summary["tweets"] = content.count("**Tweet ID:** TW_")

        # Count total characters (rough estimate)
        char_matches = content.count("**Characters:**")
        if char_matches > 0:
            summary["avg_characters"] = 150  # Estimate

    # Count pending approvals
    if PENDING_APPROVAL_DIR.exists():
        for f in PENDING_APPROVAL_DIR.glob("TWEET_*.json"):
            summary["pending_approvals"] += 1

    # Count rejected
    if REJECTED_DIR.exists():
        for f in REJECTED_DIR.glob("TWEET_*.json"):
            summary["rejected"] += 1

    return summary


def show_summary():
    """Display weekly summary."""
    summary = get_weekly_summary()

    print("\n" + "="*60)
    print("TWITTER/X WEEKLY SUMMARY")
    print("="*60)
    print(f"Period: {summary['period']['start']} to {summary['period']['end']}")
    print(f"Mode: {'MOCK' if MOCK_MODE else 'PRODUCTION'}")
    print()

    print("TWEETS")
    print(f"  Total Posted: {summary['tweets']}")
    print(f"  Avg Characters: ~{summary['avg_characters']}")
    print()

    print("ENGAGEMENT (simulated)")
    print(f"  Likes: {summary['engagement']['likes']}")
    print(f"  Retweets: {summary['engagement']['retweets']}")
    print(f"  Replies: {summary['engagement']['replies']}")
    print()

    print("WORKFLOW")
    print(f"  Pending Approvals: {summary['pending_approvals']}")
    print(f"  Rejected: {summary['rejected']}")

    print("="*60 + "\n")


def show_history():
    """Display tweet history."""
    print(f"\n{'='*60}")
    print("TWITTER/X POST HISTORY")
    print("="*60 + "\n")

    if not TWITTER_POSTS_FILE.exists():
        print("No tweets yet.")
        return

    print(TWITTER_POSTS_FILE.read_text())


def show_status():
    """Show current status of Twitter integration."""
    print("\n" + "="*60)
    print("TWITTER/X INTEGRATION STATUS")
    print("="*60)

    # Mode
    print(f"\nMode: {'MOCK (simulated)' if MOCK_MODE else 'PRODUCTION'}")
    print(f"Character Limit: {TWEET_CHAR_LIMIT}")

    # Files
    print("\nHistory:")
    if TWITTER_POSTS_FILE.exists():
        tweet_count = TWITTER_POSTS_FILE.read_text().count("**Tweet ID:** TW_")
        print(f"  Tweets: {tweet_count}")
    else:
        print("  Tweets: No tweets yet")

    # Pending
    print("\nPending Approvals:")
    if PENDING_APPROVAL_DIR.exists():
        pending = list(PENDING_APPROVAL_DIR.glob("TWEET_*.json"))
        if pending:
            for f in pending[:5]:
                data = json.loads(f.read_text())
                chars = data.get("character_count", 0)
                exceeds = " [OVER LIMIT]" if data.get("exceeds_limit") else ""
                print(f"  - ({chars} chars{exceeds}): {data['content'][:40]}...")
            if len(pending) > 5:
                print(f"  ... and {len(pending) - 5} more")
        else:
            print("  None")
    else:
        print("  None")

    print("\n" + "="*60)


def run_demo():
    """Run a full demo of Twitter integration."""
    print("\n" + "="*60)
    print("TWITTER/X INTEGRATION DEMO")
    print("="*60)
    print(f"Mode: {'MOCK (no real API calls)' if MOCK_MODE else 'PRODUCTION'}")
    print(f"Character Limit: {TWEET_CHAR_LIMIT}")
    print()

    # Demo 1: Valid tweet
    print("[1/4] Creating a valid tweet...")
    tweet1 = "Excited to share our latest AI automation features! Building the future of autonomous work. #AI #Automation #Tech"
    result1 = post_tweet(tweet1, auto_approve=False)
    length1 = len(tweet1)
    print(f"  Content: \"{tweet1[:50]}...\"")
    print(f"  Characters: {length1}/{TWEET_CHAR_LIMIT}")
    print(f"  Status: {result1['status']}")
    print(f"  Approval file: {Path(result1['approval_file']).name}")
    print()

    # Demo 2: Auto-approve and publish
    print("[2/4] Simulating approval...")
    approval_path = Path(result1['approval_file'])
    if approval_path.exists():
        APPROVED_DIR.mkdir(exist_ok=True)
        approved_path = APPROVED_DIR / approval_path.name
        shutil.move(str(approval_path), str(approved_path))
        print("  Moved to Approved folder")

        data = json.loads(approved_path.read_text())
        publish_result = mock_publish_tweet(data["tweet_id"], data["content"])
        print(f"  Tweet published (mock): {data['tweet_id']}")
    print()

    # Demo 3: Tweet with hashtags and mentions
    print("[3/4] Creating tweet with mentions...")
    tweet2 = "Great insights from @TechLeader on AI trends! The future is autonomous. #AIEmployee #FutureOfWork"
    result2 = post_tweet(tweet2, auto_approve=True)
    print(f"  Content: \"{tweet2[:50]}...\"")
    print(f"  Characters: {len(tweet2)}/{TWEET_CHAR_LIMIT}")
    print(f"  Mentions: {result2['mentions']}")
    print(f"  Hashtags: {result2['hashtags']}")
    print(f"  Status: {result2['status']}")
    print()

    # Demo 4: Show warning for long tweet
    print("[4/4] Testing character limit warning...")
    long_tweet = "This is a demonstration of what happens when a tweet exceeds the 280 character limit. " * 4
    length_info = validate_tweet_length(long_tweet)
    print(f"  Content length: {length_info['length']} characters")
    print(f"  Limit: {TWEET_CHAR_LIMIT} characters")
    print(f"  Exceeds limit by: {-length_info['remaining']} characters")
    print(f"  Status: Would be rejected/truncated")
    print()

    # Summary
    print("DEMO SUMMARY")
    print("-"*40)
    summary = get_weekly_summary()
    print(f"  Tweets published: {summary['tweets']}")
    print(f"  Pending approvals: {summary['pending_approvals']}")
    print()

    print("Demo completed successfully!")
    print("="*60 + "\n")


# === Main Entry Point ===

if __name__ == "__main__":
    if len(sys.argv) > 1:
        arg = sys.argv[1]

        if arg == "--tweet" and len(sys.argv) > 2:
            content = sys.argv[2]
            result = post_tweet(content)
            length = result["character_count"]
            limit = result["character_limit"]

            print(f"\nTweet request created!")
            print(f"Characters: {length}/{limit}")
            if result["exceeds_limit"]:
                print(f"WARNING: Exceeds limit by {length - limit} characters!")
            print(f"Status: {result['status']}")
            print(f"Approval file: {Path(result['approval_file']).name}")
            print(f"\nTo approve: Move the file to /Approved/")
            print(f"To reject: Move the file to /Rejected/")

        elif arg == "--summary":
            show_summary()

        elif arg == "--history":
            show_history()

        elif arg == "--status":
            show_status()

        elif arg == "--demo":
            run_demo()

        elif arg == "--help":
            print(__doc__)

        else:
            print(f"Unknown option: {arg}")
            print(__doc__)

    else:
        print(__doc__)
